FROM oraclelinux:7-slim

WORKDIR /mlflow

RUN yum install wget -y

ENV CONDA_HOME=/opt/miniconda3
COPY miniconda_install.sh /tmp/miniconda_install.sh
RUN sh /tmp/miniconda_install.sh

ENV PATH=$CONDA_HOME/bin:$PATH
RUN echo $PATH

COPY requirements.txt ./
RUN python -m pip install --no-cache-dir -r requirements.txt && \
    rm requirements.txt
	
EXPOSE ${PORT}
	
CMD mlflow models serve \
    --host 0.0.0.0 \
    --port ${PORT} \
    --model-uri ${MODEL_URI} 
	