FROM oraclelinux:7-slim

ARG S3_ENDPOINT_URL
ENV MLFLOW_S3_ENDPOINT_URL=$S3_ENDPOINT_URL

RUN yum install wget vim -y

ENV CONDA_HOME=/opt/miniconda3
COPY miniconda_install.sh /tmp/miniconda_install.sh
RUN sh /tmp/miniconda_install.sh

ENV PATH=$CONDA_HOME/bin:$PATH
RUN echo $PATH

COPY requirements.txt ./
RUN python -m pip install --no-cache-dir -r requirements.txt

EXPOSE 1234

